spring:
  application:
    name: mcpclient
  devtools:
    restart:
      enabled: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      client:
        stdio:
          servers-configuration: 'classpath:mcp-servers.json'
    chat:
      memory:
        enabled: true
        # For InMemoryChatMemory (default)
        store: in-memory
        # Optional: Configure capacity
        capacity: 5

logging:
  charset:
    file: UTF-8
    console: UTF-8
  pattern:
    console: '%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %blue(%-5level) %yellow(%logger{36}) - %msg%n'
  level:
    org.springframework.ai.chat.client.advisor: debug